### PR TITLE
Fixed gateone_anywhere.js and moved it to the main static directory

### PR DESCRIPTION
**Pull request by wrightrocket**
Ignore my .gitignore changes, please.

### CODE REVIEW

**Comment by wrightrocket** [comment]
Updated gateone_anywhere.js based upon http://www.liftoffsoftware.com/gateone_esc.js.  My first ever pull request, so feedback encouraged.

**Comment by wrightrocket** [comment]
I guess closing is not the right thing for me to do.  Sorry, I'm a newbie!

**Comment by marksantcroos** [comment]
@wrightrocket you can update your branch to revert the .gitignore commit and then it also disappears from the pull request.

**Comment by wrightrocket** [comment]
I will take care of it this afternoon. Thanks!

**Comment by wrightrocket** [comment]
The .gitignore file has been reverted

**Comment by liftoff** [comment]
I'll accept this but I think I'm going to change some of the error messages.  IE 10 has been out for ages =)

**Pull request merged**
